services:
  api:
    build: .
    container_name: home-assistant
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://tudruj:secret@postgres:5432/homeassistant
    depends_on:
      - postgres
    env_file:
      - .env
      - .env.local
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
      - /mnt/dysk:/mnt/dysk

  postgres:
    image: postgres:16
    container_name: home-assistant-db
    environment:
      POSTGRES_USER: tudruj
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: homeassistant
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud-storage
    ports:
      - "8080:80"
    volumes:
      - nextcloud_data:/var/www/html
      - /mnt/dysk:/mnt/dysk
    environment:
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
      - SQLITE_DATABASE=nextcloud
      - NEXTCLOUD_TRUSTED_DOMAINS=192.168.1.46
    restart: unless-stopped

  go2rtc:
    image: alexxit/go2rtc:latest
    container_name: go2rtc
    network_mode: host # Ważne dla RTSP/HomeKit w sieci lokalnej
    restart: always
    env_file:
      - .env
      - .env.local
    volumes:
      - ./go2rtc.yaml:/config/go2rtc.yaml

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:latest
    restart: unless-stopped
    profiles: ["zigbee"]
    volumes:
      - ./zigbee2mqtt-data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      # Roam free and access the frontend
      - 8099:8099
    environment:
      - TZ=Europe/Warsaw
    devices:
      - ${ZIGBEE_DEVICE}

volumes:
  pgdata:
  nextcloud_data:
